# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14pxfBD_fH-l4iVGvaYHcRRJjeBFiY-Ms

### Mount the Google Drive
"""

### Mounting the drive
from google.colab import drive
drive.mount("/content/gdrive")

"""#### Unzip the images"""

!unzip "/content/gdrive/MyDrive/yolo_object_detection/custom_data.zip" -d "/content/gdrive/MyDrive/yolo_object_detection"

"""### Clone the DarkNet"""

!git clone "https://github.com/AlexeyAB/darknet.git" "/content/gdrive/My Drive/yolo_object_detection/darknet"

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/gdrive/MyDrive/yolo_object_detection/darknet"

"""### To apply the changes and to make model ready for training we run make command"""

!make

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive/yolo_object_detection

"""### Split the data into training and testing"""

!python custom_data/creating-files-data-and-name.py

!python custom_data/creating-train-and-test-txt-files.py

!chmod 755 darknet

"""### To check whether all the codes work properly or not """

!chmod +x darknet/darknet

"""### Train the model"""

!darknet/darknet detector train custom_data/labelled_data.data darknet/cfg/yolov3_custom.cfg custom_weight/darknet53.conv.74 -dont_show

